Pets-Adpotion/Pets-Adpotion/Controllers/AnimalController.cs
using System.Data.Entity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Microsoft.EntityFrameworkCore;
using Pets_Adpotion.DAL;
using Pets_Adpotion.DAL.Entities;
using Pets_Adpotion.Helpers;
using Pets_Adpotion.Models;

namespace Pets_Adpotion.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AnimalController : Controller
    {
        private readonly DatabaseContext _context;
        private readonly IDropDownListsHelper _dropDownListsHelper;
        private readonly IAzureBlobHelper _azureBlobHelper;

        public AnimalController(DatabaseContext context, IDropDownListsHelper dropDownListsHelper, IAzureBlobHelper azureBlobHelper)
        {
            _context = context;
            _dropDownListsHelper = dropDownListsHelper;
            _azureBlobHelper = azureBlobHelper;
        }

        // GET: AnimalController
        public async Task<ActionResult> Index()
        {
            return View(await _context.Animals                          
                            .ToListAsync());
        }

        // GET: AnimalController/Details/5
        public async Task<ActionResult> Details(Guid? animalId)
        {
            if (animalId == null) return NotFound();

            Animal animal = await _context.Animals         
                .FirstOrDefaultAsync(a => a.Id == animalId);
            if (animal == null) return NotFound();

            return View(animal);
        }

        // GET: AnimalController/Create
        public async  Task<ActionResult> Create()
        {
            AddAnimalViewModel addAnimalViewModel = new()
            {
                AnimalTypes = await _dropDownListsHelper.GetDDLTypesAsync(),
            };

            return View(addAnimalViewModel);
           
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddAnimalViewModel addAnimalViewModel)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    Guid imageId = Guid.Empty;

                    if (addAnimalViewModel.ImageFile != null)
                        imageId = await _azureBlobHelper.UploadAzureBlobAsync(addAnimalViewModel.ImageFile, "products");

                    Animal animal = new()
                    {
                        Description = addAnimalViewModel.Description,
                        Name = addAnimalViewModel.Name,
                        Age = addAnimalViewModel.Age,
                        ImageId = imageId   
                    };

                    

                    

                    _context.Add(animal);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            addAnimalViewModel.AnimalTypes = await _dropDownListsHelper.GetDDLTypesAsync();
            return View(addAnimalViewModel);
        }


        // GET: AnimalController/Edit/5
        public async Task<ActionResult> EditAsync(Guid? animalId)
        {
            if (animalId == null) return NotFound();

            Animal animal = await _context.Animals.FindAsync(animalId);
            if (animal == null) return NotFound();

            EditAnimalViewModel editAnimalViewModel = new()
            {
                Description = animal.Description,
                Id = animal.Id,
                Name = animal.Name,
                Age = animal.Age,
               
            };

            return View(editAnimalViewModel);
        }

        // POST: AnimalController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditAsync(Guid? Id, EditAnimalViewModel editAnimalViewModel)
        {
            if (Id != editAnimalViewModel.Id) return NotFound();

            try
            {
                Animal animal = await _context.Animals.FindAsync(editAnimalViewModel.Id);
                animal.Description = editAnimalViewModel.Description;
                animal.Name = editAnimalViewModel.Name;
                animal.Age = editAnimalViewModel.Age;
                
                _context.Update(animal);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
           
            catch (Exception exception)
            {
                ModelState.AddModelError(string.Empty, exception.Message);
            }

            return View(editAnimalViewModel);
        }

        // GET: AnimalController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AnimalController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteAsync(Animal animalModel)
        {
            Animal animal = await _context.Animals
                .FirstOrDefaultAsync(p => p.Id == animalModel.Id);

            _context.Animals.Remove(animal);
            await _context.SaveChangesAsync();

           

            return RedirectToAction(nameof(Index));
        }
    }
}

Pets-Adpotion/Pets-Adpotion/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Pets_Adpotion</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Pets_Adpotion.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ECommerce_MW</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Políticas de Privacidad</a>
                        </li>
                        @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Create">Agregar Mascotas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Animal" asp-action="Index">Mascotas</a>
                            </li>                         
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Usuarios</a>
                            </li>
                        }
                        else if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                        {
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Create"> Adoptar</a>
                            </li>
                            
                        }
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="EditUser">@ViewBag.UserFullName</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Cerrar Sesión</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Iniciar Sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Pets_Adpotion - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>